name: Verify PR Requirements
on:
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  check-pr-requirements:
    name: Ensure PR Meets Requirements
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      #   - name: Install dependencies
      #     run: pip install -r requirements.txt

      - name: Check PR Header
        run: |
          title="${{ github.event.pull_request.title }}"
          if [[ $title =~ [[:punct:]] ]]; then
              echo "Pull request title contains punctuation."
              exit 1
          fi

      - name: Check PR Assignee
        run: |
          assignee="${{ github.event.pull_request.assignee }}"
          if [ -z "$assignee" ]; then
            echo "Pull request is not assigned to anyone."
            exit 1
          fi
