name: Pull Request Checks
on:
  pull_request:
    types: [edited, synchronize, opened, reopened]

jobs:
  check-issue-requirements:
    name: Check Issue Requirements
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      #   - name: Install dependencies
      #     run: pip install -r requirements.txt

      - name: Check issue requirements
        run: |
          title="${{ github.event.pull_request.title }}"
          if [[ $title =~ [[:punct:]] ]]; then
            echo "Pull request title contains punctuation."
            exit 1
          else
            echo "Pull request title does not contain punctuation."
            exit 0
          fi
